pipeline {
    agent any
    stages {
        stage('create directory and move in') 
		{
			steps{
				sh '''
					echo "creating directory"
					mkdir my_portfolio
					cd my_portfolio
				'''
			}	
		}
		stage('clone repo')
		{
			steps{
				sh '''
					git clone https://github.com/Prajjwal998/Portfolio.git
					cd Portfolio
					ls
				'''
			}
		}
	stage('execute dockerfile')
	{
		steps{
			sh '''
				docker build -t prajjwal ./docker-file
				echo "list images"
				docker images
			'''
}
	}
	stage('map port 80')
		{
			steps{
				sh '''
					docker run -itd -p 80:80 --name web prajjwal
				'''
			}
		}

	}
}
